In [ ]:
import numpy as np
# speed, efficiency, abstraction , memory optimization, homogeneous data type, continuous memory

In [2]:
my_var = np.array([12, 10, 4, 5, 32, 5])
print(my_var)

[12 10  4  5 32  5]


In [3]:
my_var1 = np.array([12, 10, 4, 5, 32, 5.5])
print(my_var1)

[12.  10.   4.   5.  32.   5.5]


In [ ]:
# list
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = list1 + list2
print(list3)

list4 = list1 * 3
print(list4)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [9]:
# numpy
l1 = np.array(list1)
l2 = np.array(list2)

print(l1, l2)
print(f"Addition {l1+l2}")
print(f"Subtraction {l1-l2}")
print(f"Multiplication {l1*l2}")
print(f"Division {l1/l2}")

[1 2 3] [4 5 6]
Addition [5 7 9]
Subtraction [-3 -3 -3]
Multiplication [ 4 10 18]
Division [0.25 0.4  0.5 ]


In [ ]:
list5 = [[1,2,3], [4,5,6], [7,8,9]]
list6 = [[0,1,2], [3,4,5], [6,7,8]]
print(list5)
print(list6)

# result = [[0,0,0], [0,0,0], [0,0,0]]
# for i in range(len(list5)):
#     for j in range(len(list6[0])):
#         for k in range(len(list6)):
#             result[i][j] += list5[i][k] * list6[k][j]

# for row in result:
#     print(row)



[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[24, 30, 36]
[51, 66, 81]
[78, 102, 126]


In [ ]:
l = [[1,2,3], [4,5,6]]
len(l)
# rows count

2

In [ ]:
len(l[0])
# columns count

3

In [19]:

# using first thought principle // list
import time
start_time = time.perf_counter()

rows_a = len(list5)
cols_a = len(list5[0])
rows_b = len(list6)
cols_b = len(list6[0])

if cols_a != rows_b:
    print ("Invalid matrix dimensons")
else:
    list3 = [[0 for _ in range(cols_b)] for _ in range(rows_a)] 
    for row in range(rows_a):
        for col in range(cols_b):
            sum_product = 0
            for element in range(cols_a):
                sum_product += list5[row][element] * list6[element][col] 
            list3[row][col] = sum_product
    print (list3)

tot_run_time = time.perf_counter() - start_time
print(f"Total elapsed time is: {tot_run_time}")

[[24, 30, 36], [51, 66, 81], [78, 102, 126]]
Total elapsed time is: 0.0008780000061960891


In [22]:
import time
import numpy as np
start_time = time.perf_counter()

# using numpy array
li1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
li2 = np.array([[0,1,2], [3,4,5], [6,7,8]])

li3 = li1 @ li2
print(li3)
tot_run_time = time.perf_counter() - start_time
print(f"Total elapsed time is: {tot_run_time}")

[[ 24  30  36]
 [ 51  66  81]
 [ 78 102 126]]
Total elapsed time is: 0.0038843000074848533


In [24]:
### Array Attributes
# plane --> ndim - number of dimensions of array is contained in ndim attribute
print(f"Dimension of Array li1 is : {li1.ndim}")

# vector --> shape - shape of array is tuple of non-negative integers for each dimensions
print(f"Shape of Array li1 is : {li1.shape}")

## Total number of elements in array is contained for each dimension
print(f"Size of Array li1 is : {li1.size}")

## dtype attributes describes the data types
print(f"Data Type of Array li1 is : {li1.dtype}")

Dimension of Array li1 is : 2
Shape of Array li1 is : (3, 3)
Size of Array li1 is : 9
Data Type of Array li1 is : int64
